### ISSUE TITLE
Issue with mypi in the Commits

### ISSUE THREAD

**Issue by Mohini-Shrivastava** [torch-spyre/hf-adapters#294]
After the merge commit `6b0d830` , following error is observed in the commit for subsequent PRs:
```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

hf_adapters/_dspark_common.py:402: error: Cannot find implementation or library stub for module named "deepspec.utils.sampling" [import-not-found]
hf_adapters/hf_dspark_qwen3.py:55: error: Cannot find implementation or library stub for module named "deepspec.modeling.dspark.qwen3.modeling" [import-not-found]
hf_adapters/hf_dspark_gemma4.py:135: error: Cannot find implementation or library stub for module named "deepspec.modeling.dspark.gemma4.modeling" [import-not-found]
hf_adapters/hf_dspark_gemma4.py:135: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 3 errors in 3 files (checked 1 source file)
```
